// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package structures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserToNetworkRequirements struct {
	NumSeamlessTrees     uint32   `protobuf:"varint,1,opt,name=NumSeamlessTrees,json=num-seamless-trees,proto3" json:"NumSeamlessTrees,omitempty"`
	MaxLatency           uint32   `protobuf:"varint,2,opt,name=MaxLatency,json=max-latency,proto3" json:"MaxLatency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToNetworkRequirements) Reset()         { *m = UserToNetworkRequirements{} }
func (m *UserToNetworkRequirements) String() string { return proto.CompactTextString(m) }
func (*UserToNetworkRequirements) ProtoMessage()    {}
func (*UserToNetworkRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *UserToNetworkRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToNetworkRequirements.Unmarshal(m, b)
}
func (m *UserToNetworkRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToNetworkRequirements.Marshal(b, m, deterministic)
}
func (m *UserToNetworkRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToNetworkRequirements.Merge(m, src)
}
func (m *UserToNetworkRequirements) XXX_Size() int {
	return xxx_messageInfo_UserToNetworkRequirements.Size(m)
}
func (m *UserToNetworkRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToNetworkRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_UserToNetworkRequirements proto.InternalMessageInfo

func (m *UserToNetworkRequirements) GetNumSeamlessTrees() uint32 {
	if m != nil {
		return m.NumSeamlessTrees
	}
	return 0
}

func (m *UserToNetworkRequirements) GetMaxLatency() uint32 {
	if m != nil {
		return m.MaxLatency
	}
	return 0
}

type InterfaceCapabilities struct {
	VlanTagCapable       bool     `protobuf:"varint,1,opt,name=VlanTagCapable,json=vlan-tag-capable,proto3" json:"VlanTagCapable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceCapabilities) Reset()         { *m = InterfaceCapabilities{} }
func (m *InterfaceCapabilities) String() string { return proto.CompactTextString(m) }
func (*InterfaceCapabilities) ProtoMessage()    {}
func (*InterfaceCapabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *InterfaceCapabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceCapabilities.Unmarshal(m, b)
}
func (m *InterfaceCapabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceCapabilities.Marshal(b, m, deterministic)
}
func (m *InterfaceCapabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceCapabilities.Merge(m, src)
}
func (m *InterfaceCapabilities) XXX_Size() int {
	return xxx_messageInfo_InterfaceCapabilities.Size(m)
}
func (m *InterfaceCapabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceCapabilities.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceCapabilities proto.InternalMessageInfo

func (m *InterfaceCapabilities) GetVlanTagCapable() bool {
	if m != nil {
		return m.VlanTagCapable
	}
	return false
}

type StreamId struct {
	MacAddress           string   `protobuf:"bytes,1,opt,name=MacAddress,json=mac-address,proto3" json:"MacAddress,omitempty"`
	UniqueId             string   `protobuf:"bytes,2,opt,name=UniqueId,json=unique-id,proto3" json:"UniqueId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamId) Reset()         { *m = StreamId{} }
func (m *StreamId) String() string { return proto.CompactTextString(m) }
func (*StreamId) ProtoMessage()    {}
func (*StreamId) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

func (m *StreamId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamId.Unmarshal(m, b)
}
func (m *StreamId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamId.Marshal(b, m, deterministic)
}
func (m *StreamId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamId.Merge(m, src)
}
func (m *StreamId) XXX_Size() int {
	return xxx_messageInfo_StreamId.Size(m)
}
func (m *StreamId) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamId.DiscardUnknown(m)
}

var xxx_messageInfo_StreamId proto.InternalMessageInfo

func (m *StreamId) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *StreamId) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

type InterfaceId struct {
	MacAddress           string   `protobuf:"bytes,1,opt,name=MacAddress,json=mac-address,proto3" json:"MacAddress,omitempty"`
	InterfaceName        string   `protobuf:"bytes,2,opt,name=InterfaceName,json=interface-name,proto3" json:"InterfaceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceId) Reset()         { *m = InterfaceId{} }
func (m *InterfaceId) String() string { return proto.CompactTextString(m) }
func (*InterfaceId) ProtoMessage()    {}
func (*InterfaceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{3}
}

func (m *InterfaceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceId.Unmarshal(m, b)
}
func (m *InterfaceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceId.Marshal(b, m, deterministic)
}
func (m *InterfaceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceId.Merge(m, src)
}
func (m *InterfaceId) XXX_Size() int {
	return xxx_messageInfo_InterfaceId.Size(m)
}
func (m *InterfaceId) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceId.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceId proto.InternalMessageInfo

func (m *InterfaceId) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *InterfaceId) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

type Interface struct {
	Index                int64        `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	InterfaceId          *InterfaceId `protobuf:"bytes,2,opt,name=InterfaceId,json=interface-id,proto3" json:"InterfaceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{4}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Interface) GetInterfaceId() *InterfaceId {
	if m != nil {
		return m.InterfaceId
	}
	return nil
}

type ListenerGroup struct {
	Index                uint32                     `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	StrId                *StreamId                  `protobuf:"bytes,2,opt,name=StrId,json=stream-id,proto3" json:"StrId,omitempty"`
	EndStationInterfaces []*Interface               `protobuf:"bytes,3,rep,name=EndStationInterfaces,json=end-station-interfaces,proto3" json:"EndStationInterfaces,omitempty"`
	UserToNetReq         *UserToNetworkRequirements `protobuf:"bytes,4,opt,name=UserToNetReq,json=user-to-network-requirements,proto3" json:"UserToNetReq,omitempty"`
	InterfCap            *InterfaceCapabilities     `protobuf:"bytes,5,opt,name=InterfCap,json=interface-capabilities,proto3" json:"InterfCap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListenerGroup) Reset()         { *m = ListenerGroup{} }
func (m *ListenerGroup) String() string { return proto.CompactTextString(m) }
func (*ListenerGroup) ProtoMessage()    {}
func (*ListenerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{5}
}

func (m *ListenerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerGroup.Unmarshal(m, b)
}
func (m *ListenerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerGroup.Marshal(b, m, deterministic)
}
func (m *ListenerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerGroup.Merge(m, src)
}
func (m *ListenerGroup) XXX_Size() int {
	return xxx_messageInfo_ListenerGroup.Size(m)
}
func (m *ListenerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerGroup proto.InternalMessageInfo

func (m *ListenerGroup) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ListenerGroup) GetStrId() *StreamId {
	if m != nil {
		return m.StrId
	}
	return nil
}

func (m *ListenerGroup) GetEndStationInterfaces() []*Interface {
	if m != nil {
		return m.EndStationInterfaces
	}
	return nil
}

func (m *ListenerGroup) GetUserToNetReq() *UserToNetworkRequirements {
	if m != nil {
		return m.UserToNetReq
	}
	return nil
}

func (m *ListenerGroup) GetInterfCap() *InterfaceCapabilities {
	if m != nil {
		return m.InterfCap
	}
	return nil
}

type StreamRank struct {
	Rank                 uint32   `protobuf:"varint,1,opt,name=Rank,json=rank,proto3" json:"Rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRank) Reset()         { *m = StreamRank{} }
func (m *StreamRank) String() string { return proto.CompactTextString(m) }
func (*StreamRank) ProtoMessage()    {}
func (*StreamRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{6}
}

func (m *StreamRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRank.Unmarshal(m, b)
}
func (m *StreamRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRank.Marshal(b, m, deterministic)
}
func (m *StreamRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRank.Merge(m, src)
}
func (m *StreamRank) XXX_Size() int {
	return xxx_messageInfo_StreamRank.Size(m)
}
func (m *StreamRank) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRank.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRank proto.InternalMessageInfo

func (m *StreamRank) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type IeeeMacAddress struct {
	DestinationMac       string   `protobuf:"bytes,1,opt,name=DestinationMac,json=destination-mac-address,proto3" json:"DestinationMac,omitempty"`
	SourceMac            string   `protobuf:"bytes,2,opt,name=SourceMac,json=source-mac,proto3" json:"SourceMac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IeeeMacAddress) Reset()         { *m = IeeeMacAddress{} }
func (m *IeeeMacAddress) String() string { return proto.CompactTextString(m) }
func (*IeeeMacAddress) ProtoMessage()    {}
func (*IeeeMacAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{7}
}

func (m *IeeeMacAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IeeeMacAddress.Unmarshal(m, b)
}
func (m *IeeeMacAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IeeeMacAddress.Marshal(b, m, deterministic)
}
func (m *IeeeMacAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IeeeMacAddress.Merge(m, src)
}
func (m *IeeeMacAddress) XXX_Size() int {
	return xxx_messageInfo_IeeeMacAddress.Size(m)
}
func (m *IeeeMacAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_IeeeMacAddress.DiscardUnknown(m)
}

var xxx_messageInfo_IeeeMacAddress proto.InternalMessageInfo

func (m *IeeeMacAddress) GetDestinationMac() string {
	if m != nil {
		return m.DestinationMac
	}
	return ""
}

func (m *IeeeMacAddress) GetSourceMac() string {
	if m != nil {
		return m.SourceMac
	}
	return ""
}

type IeeeVlanTag struct {
	PriorityCodePoint    uint32   `protobuf:"varint,1,opt,name=PriorityCodePoint,json=priority-code-point,proto3" json:"PriorityCodePoint,omitempty"`
	VlanId               uint32   `protobuf:"varint,2,opt,name=VlanId,json=vlan-id,proto3" json:"VlanId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IeeeVlanTag) Reset()         { *m = IeeeVlanTag{} }
func (m *IeeeVlanTag) String() string { return proto.CompactTextString(m) }
func (*IeeeVlanTag) ProtoMessage()    {}
func (*IeeeVlanTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{8}
}

func (m *IeeeVlanTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IeeeVlanTag.Unmarshal(m, b)
}
func (m *IeeeVlanTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IeeeVlanTag.Marshal(b, m, deterministic)
}
func (m *IeeeVlanTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IeeeVlanTag.Merge(m, src)
}
func (m *IeeeVlanTag) XXX_Size() int {
	return xxx_messageInfo_IeeeVlanTag.Size(m)
}
func (m *IeeeVlanTag) XXX_DiscardUnknown() {
	xxx_messageInfo_IeeeVlanTag.DiscardUnknown(m)
}

var xxx_messageInfo_IeeeVlanTag proto.InternalMessageInfo

func (m *IeeeVlanTag) GetPriorityCodePoint() uint32 {
	if m != nil {
		return m.PriorityCodePoint
	}
	return 0
}

func (m *IeeeVlanTag) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

type Ipv4Tuple struct {
	SrcIpAddr            string   `protobuf:"bytes,1,opt,name=SrcIpAddr,json=src-ip-addr,proto3" json:"SrcIpAddr,omitempty"`
	DestIpAddr           string   `protobuf:"bytes,2,opt,name=DestIpAddr,json=dest-ip-addr,proto3" json:"DestIpAddr,omitempty"`
	Dscp                 uint32   `protobuf:"varint,3,opt,name=Dscp,json=dscp,proto3" json:"Dscp,omitempty"`
	Protocol             uint32   `protobuf:"varint,4,opt,name=Protocol,json=protocol,proto3" json:"Protocol,omitempty"`
	SrcPort              uint32   `protobuf:"varint,5,opt,name=SrcPort,json=src-port,proto3" json:"SrcPort,omitempty"`
	DestPort             uint32   `protobuf:"varint,6,opt,name=DestPort,json=dest-port,proto3" json:"DestPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipv4Tuple) Reset()         { *m = Ipv4Tuple{} }
func (m *Ipv4Tuple) String() string { return proto.CompactTextString(m) }
func (*Ipv4Tuple) ProtoMessage()    {}
func (*Ipv4Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{9}
}

func (m *Ipv4Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipv4Tuple.Unmarshal(m, b)
}
func (m *Ipv4Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipv4Tuple.Marshal(b, m, deterministic)
}
func (m *Ipv4Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipv4Tuple.Merge(m, src)
}
func (m *Ipv4Tuple) XXX_Size() int {
	return xxx_messageInfo_Ipv4Tuple.Size(m)
}
func (m *Ipv4Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipv4Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Ipv4Tuple proto.InternalMessageInfo

func (m *Ipv4Tuple) GetSrcIpAddr() string {
	if m != nil {
		return m.SrcIpAddr
	}
	return ""
}

func (m *Ipv4Tuple) GetDestIpAddr() string {
	if m != nil {
		return m.DestIpAddr
	}
	return ""
}

func (m *Ipv4Tuple) GetDscp() uint32 {
	if m != nil {
		return m.Dscp
	}
	return 0
}

func (m *Ipv4Tuple) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Ipv4Tuple) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Ipv4Tuple) GetDestPort() uint32 {
	if m != nil {
		return m.DestPort
	}
	return 0
}

type Ipv6Tuple struct {
	SrcIpAddr            string   `protobuf:"bytes,1,opt,name=SrcIpAddr,json=src-ip-addr,proto3" json:"SrcIpAddr,omitempty"`
	DestIpAddr           string   `protobuf:"bytes,2,opt,name=DestIpAddr,json=dest-ip-addr,proto3" json:"DestIpAddr,omitempty"`
	Dscp                 uint32   `protobuf:"varint,3,opt,name=Dscp,json=dscp,proto3" json:"Dscp,omitempty"`
	Protocol             uint32   `protobuf:"varint,4,opt,name=Protocol,json=protocol,proto3" json:"Protocol,omitempty"`
	SrcPort              uint32   `protobuf:"varint,5,opt,name=SrcPort,json=src-port,proto3" json:"SrcPort,omitempty"`
	DestPort             uint32   `protobuf:"varint,6,opt,name=DestPort,json=dest-port,proto3" json:"DestPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipv6Tuple) Reset()         { *m = Ipv6Tuple{} }
func (m *Ipv6Tuple) String() string { return proto.CompactTextString(m) }
func (*Ipv6Tuple) ProtoMessage()    {}
func (*Ipv6Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{10}
}

func (m *Ipv6Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipv6Tuple.Unmarshal(m, b)
}
func (m *Ipv6Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipv6Tuple.Marshal(b, m, deterministic)
}
func (m *Ipv6Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipv6Tuple.Merge(m, src)
}
func (m *Ipv6Tuple) XXX_Size() int {
	return xxx_messageInfo_Ipv6Tuple.Size(m)
}
func (m *Ipv6Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipv6Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Ipv6Tuple proto.InternalMessageInfo

func (m *Ipv6Tuple) GetSrcIpAddr() string {
	if m != nil {
		return m.SrcIpAddr
	}
	return ""
}

func (m *Ipv6Tuple) GetDestIpAddr() string {
	if m != nil {
		return m.DestIpAddr
	}
	return ""
}

func (m *Ipv6Tuple) GetDscp() uint32 {
	if m != nil {
		return m.Dscp
	}
	return 0
}

func (m *Ipv6Tuple) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Ipv6Tuple) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Ipv6Tuple) GetDestPort() uint32 {
	if m != nil {
		return m.DestPort
	}
	return 0
}

type DataFrameSpecification struct {
	Index                uint32          `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	MacAddr              *IeeeMacAddress `protobuf:"bytes,2,opt,name=MacAddr,json=ieee802-mac-addresses,proto3" json:"MacAddr,omitempty"`
	VlanTag              *IeeeVlanTag    `protobuf:"bytes,3,opt,name=VlanTag,json=ieee802-vlan-tag,proto3" json:"VlanTag,omitempty"`
	Ipv4Tup              *Ipv4Tuple      `protobuf:"bytes,4,opt,name=Ipv4Tup,json=ipv4tup,proto3" json:"Ipv4Tup,omitempty"`
	Ipv6Tup              *Ipv6Tuple      `protobuf:"bytes,5,opt,name=Ipv6Tup,json=ipv6tup,proto3" json:"Ipv6Tup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DataFrameSpecification) Reset()         { *m = DataFrameSpecification{} }
func (m *DataFrameSpecification) String() string { return proto.CompactTextString(m) }
func (*DataFrameSpecification) ProtoMessage()    {}
func (*DataFrameSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{11}
}

func (m *DataFrameSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFrameSpecification.Unmarshal(m, b)
}
func (m *DataFrameSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFrameSpecification.Marshal(b, m, deterministic)
}
func (m *DataFrameSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFrameSpecification.Merge(m, src)
}
func (m *DataFrameSpecification) XXX_Size() int {
	return xxx_messageInfo_DataFrameSpecification.Size(m)
}
func (m *DataFrameSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFrameSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_DataFrameSpecification proto.InternalMessageInfo

func (m *DataFrameSpecification) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DataFrameSpecification) GetMacAddr() *IeeeMacAddress {
	if m != nil {
		return m.MacAddr
	}
	return nil
}

func (m *DataFrameSpecification) GetVlanTag() *IeeeVlanTag {
	if m != nil {
		return m.VlanTag
	}
	return nil
}

func (m *DataFrameSpecification) GetIpv4Tup() *Ipv4Tuple {
	if m != nil {
		return m.Ipv4Tup
	}
	return nil
}

func (m *DataFrameSpecification) GetIpv6Tup() *Ipv6Tuple {
	if m != nil {
		return m.Ipv6Tup
	}
	return nil
}

type Interval struct {
	Numerator            uint32   `protobuf:"varint,1,opt,name=Numerator,json=numerator,proto3" json:"Numerator,omitempty"`
	Denominator          uint32   `protobuf:"varint,2,opt,name=Denominator,json=denominator,proto3" json:"Denominator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interval) Reset()         { *m = Interval{} }
func (m *Interval) String() string { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()    {}
func (*Interval) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{12}
}

func (m *Interval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interval.Unmarshal(m, b)
}
func (m *Interval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interval.Marshal(b, m, deterministic)
}
func (m *Interval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interval.Merge(m, src)
}
func (m *Interval) XXX_Size() int {
	return xxx_messageInfo_Interval.Size(m)
}
func (m *Interval) XXX_DiscardUnknown() {
	xxx_messageInfo_Interval.DiscardUnknown(m)
}

var xxx_messageInfo_Interval proto.InternalMessageInfo

func (m *Interval) GetNumerator() uint32 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Interval) GetDenominator() uint32 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

type TimeAware struct {
	EarliestTransmitOffset uint32   `protobuf:"varint,1,opt,name=EarliestTransmitOffset,json=earliest-transmit-offset,proto3" json:"EarliestTransmitOffset,omitempty"`
	LatestTransmitOffset   uint32   `protobuf:"varint,2,opt,name=LatestTransmitOffset,json=latest-transmit-offset,proto3" json:"LatestTransmitOffset,omitempty"`
	Jitter                 uint32   `protobuf:"varint,3,opt,name=Jitter,json=jitter,proto3" json:"Jitter,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TimeAware) Reset()         { *m = TimeAware{} }
func (m *TimeAware) String() string { return proto.CompactTextString(m) }
func (*TimeAware) ProtoMessage()    {}
func (*TimeAware) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{13}
}

func (m *TimeAware) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeAware.Unmarshal(m, b)
}
func (m *TimeAware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeAware.Marshal(b, m, deterministic)
}
func (m *TimeAware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeAware.Merge(m, src)
}
func (m *TimeAware) XXX_Size() int {
	return xxx_messageInfo_TimeAware.Size(m)
}
func (m *TimeAware) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeAware.DiscardUnknown(m)
}

var xxx_messageInfo_TimeAware proto.InternalMessageInfo

func (m *TimeAware) GetEarliestTransmitOffset() uint32 {
	if m != nil {
		return m.EarliestTransmitOffset
	}
	return 0
}

func (m *TimeAware) GetLatestTransmitOffset() uint32 {
	if m != nil {
		return m.LatestTransmitOffset
	}
	return 0
}

func (m *TimeAware) GetJitter() uint32 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

type TrafficSpecification struct {
	Interval              *Interval  `protobuf:"bytes,1,opt,name=Interval,json=interval,proto3" json:"Interval,omitempty"`
	MaxFramesPerInterval  uint32     `protobuf:"varint,2,opt,name=MaxFramesPerInterval,json=max-frames-per-interval,proto3" json:"MaxFramesPerInterval,omitempty"`
	MaxFrameSize          uint32     `protobuf:"varint,3,opt,name=MaxFrameSize,json=max-frame-size,proto3" json:"MaxFrameSize,omitempty"`
	TransmissionSelection uint32     `protobuf:"varint,4,opt,name=TransmissionSelection,json=transmission-selection,proto3" json:"TransmissionSelection,omitempty"`
	TimeAware             *TimeAware `protobuf:"bytes,5,opt,name=TimeAware,json=time-aware,proto3" json:"TimeAware,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *TrafficSpecification) Reset()         { *m = TrafficSpecification{} }
func (m *TrafficSpecification) String() string { return proto.CompactTextString(m) }
func (*TrafficSpecification) ProtoMessage()    {}
func (*TrafficSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{14}
}

func (m *TrafficSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficSpecification.Unmarshal(m, b)
}
func (m *TrafficSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficSpecification.Marshal(b, m, deterministic)
}
func (m *TrafficSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficSpecification.Merge(m, src)
}
func (m *TrafficSpecification) XXX_Size() int {
	return xxx_messageInfo_TrafficSpecification.Size(m)
}
func (m *TrafficSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficSpecification proto.InternalMessageInfo

func (m *TrafficSpecification) GetInterval() *Interval {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *TrafficSpecification) GetMaxFramesPerInterval() uint32 {
	if m != nil {
		return m.MaxFramesPerInterval
	}
	return 0
}

func (m *TrafficSpecification) GetMaxFrameSize() uint32 {
	if m != nil {
		return m.MaxFrameSize
	}
	return 0
}

func (m *TrafficSpecification) GetTransmissionSelection() uint32 {
	if m != nil {
		return m.TransmissionSelection
	}
	return 0
}

func (m *TrafficSpecification) GetTimeAware() *TimeAware {
	if m != nil {
		return m.TimeAware
	}
	return nil
}

type TalkerGroup struct {
	StrId                  *StreamId                  `protobuf:"bytes,1,opt,name=StrId,json=stream-id,proto3" json:"StrId,omitempty"`
	StrRank                *StreamRank                `protobuf:"bytes,2,opt,name=StrRank,json=stream-rank,proto3" json:"StrRank,omitempty"`
	EndStationInterfaces   []*Interface               `protobuf:"bytes,3,rep,name=EndStationInterfaces,json=end-station-interfaces,proto3" json:"EndStationInterfaces,omitempty"`
	DataFrameSpecification []*DataFrameSpecification  `protobuf:"bytes,4,rep,name=DataFrameSpecification,json=data-frame-specification,proto3" json:"DataFrameSpecification,omitempty"`
	TrafficSpecification   *TrafficSpecification      `protobuf:"bytes,5,opt,name=TrafficSpecification,json=traffic-specification,proto3" json:"TrafficSpecification,omitempty"`
	UserToNetReq           *UserToNetworkRequirements `protobuf:"bytes,6,opt,name=UserToNetReq,json=user-to-network-requirements,proto3" json:"UserToNetReq,omitempty"`
	InterfCap              *InterfaceCapabilities     `protobuf:"bytes,7,opt,name=InterfCap,json=interface-capabilities,proto3" json:"InterfCap,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                   `json:"-"`
	XXX_unrecognized       []byte                     `json:"-"`
	XXX_sizecache          int32                      `json:"-"`
}

func (m *TalkerGroup) Reset()         { *m = TalkerGroup{} }
func (m *TalkerGroup) String() string { return proto.CompactTextString(m) }
func (*TalkerGroup) ProtoMessage()    {}
func (*TalkerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{15}
}

func (m *TalkerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TalkerGroup.Unmarshal(m, b)
}
func (m *TalkerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TalkerGroup.Marshal(b, m, deterministic)
}
func (m *TalkerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TalkerGroup.Merge(m, src)
}
func (m *TalkerGroup) XXX_Size() int {
	return xxx_messageInfo_TalkerGroup.Size(m)
}
func (m *TalkerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TalkerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TalkerGroup proto.InternalMessageInfo

func (m *TalkerGroup) GetStrId() *StreamId {
	if m != nil {
		return m.StrId
	}
	return nil
}

func (m *TalkerGroup) GetStrRank() *StreamRank {
	if m != nil {
		return m.StrRank
	}
	return nil
}

func (m *TalkerGroup) GetEndStationInterfaces() []*Interface {
	if m != nil {
		return m.EndStationInterfaces
	}
	return nil
}

func (m *TalkerGroup) GetDataFrameSpecification() []*DataFrameSpecification {
	if m != nil {
		return m.DataFrameSpecification
	}
	return nil
}

func (m *TalkerGroup) GetTrafficSpecification() *TrafficSpecification {
	if m != nil {
		return m.TrafficSpecification
	}
	return nil
}

func (m *TalkerGroup) GetUserToNetReq() *UserToNetworkRequirements {
	if m != nil {
		return m.UserToNetReq
	}
	return nil
}

func (m *TalkerGroup) GetInterfCap() *InterfaceCapabilities {
	if m != nil {
		return m.InterfCap
	}
	return nil
}

type Request struct {
	Talker               *TalkerGroup     `protobuf:"bytes,1,opt,name=Talker,json=talker,proto3" json:"Talker,omitempty"`
	ListenerList         []*ListenerGroup `protobuf:"bytes,2,rep,name=ListenerList,json=listener-list,proto3" json:"ListenerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{16}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTalker() *TalkerGroup {
	if m != nil {
		return m.Talker
	}
	return nil
}

func (m *Request) GetListenerList() []*ListenerGroup {
	if m != nil {
		return m.ListenerList
	}
	return nil
}

type ConfigRequest struct {
	Version              float32    `protobuf:"fixed32,1,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Requests             []*Request `protobuf:"bytes,2,rep,name=Requests,json=requests,proto3" json:"Requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{17}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigRequest) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*UserToNetworkRequirements)(nil), "structures.UserToNetworkRequirements")
	proto.RegisterType((*InterfaceCapabilities)(nil), "structures.InterfaceCapabilities")
	proto.RegisterType((*StreamId)(nil), "structures.StreamId")
	proto.RegisterType((*InterfaceId)(nil), "structures.InterfaceId")
	proto.RegisterType((*Interface)(nil), "structures.Interface")
	proto.RegisterType((*ListenerGroup)(nil), "structures.ListenerGroup")
	proto.RegisterType((*StreamRank)(nil), "structures.StreamRank")
	proto.RegisterType((*IeeeMacAddress)(nil), "structures.IeeeMacAddress")
	proto.RegisterType((*IeeeVlanTag)(nil), "structures.IeeeVlanTag")
	proto.RegisterType((*Ipv4Tuple)(nil), "structures.Ipv4Tuple")
	proto.RegisterType((*Ipv6Tuple)(nil), "structures.Ipv6Tuple")
	proto.RegisterType((*DataFrameSpecification)(nil), "structures.DataFrameSpecification")
	proto.RegisterType((*Interval)(nil), "structures.Interval")
	proto.RegisterType((*TimeAware)(nil), "structures.TimeAware")
	proto.RegisterType((*TrafficSpecification)(nil), "structures.TrafficSpecification")
	proto.RegisterType((*TalkerGroup)(nil), "structures.TalkerGroup")
	proto.RegisterType((*Request)(nil), "structures.Request")
	proto.RegisterType((*ConfigRequest)(nil), "structures.ConfigRequest")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 1151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x57, 0x1c, 0xc7, 0xf6, 0x8d, 0xe3, 0xa8, 0x6c, 0x1d, 0xc7, 0x2d, 0x05, 0xcc, 0x89, 0x4a,
	0x7d, 0x60, 0x93, 0xaa, 0xa4, 0x55, 0xd5, 0x07, 0xa4, 0x92, 0x14, 0x70, 0x69, 0x43, 0xb4, 0x76,
	0x2a, 0x81, 0x40, 0x62, 0x7b, 0x37, 0x8e, 0xb6, 0xb9, 0x7f, 0xd9, 0xdd, 0x4b, 0xd3, 0x7c, 0x0a,
	0x04, 0xef, 0x7c, 0x0b, 0x3e, 0x05, 0x5f, 0x0a, 0xed, 0xde, 0xde, 0xf9, 0x9c, 0x38, 0x52, 0x25,
	0xe0, 0x81, 0x27, 0x7b, 0xe7, 0x37, 0xff, 0x76, 0xe6, 0x37, 0x3b, 0x07, 0x37, 0x83, 0x34, 0x99,
	0x89, 0xe3, 0x5c, 0x72, 0x2d, 0xd2, 0x64, 0x3b, 0x93, 0xa9, 0x4e, 0x09, 0x28, 0x2d, 0xf3, 0x40,
	0xe7, 0x12, 0x95, 0xff, 0x06, 0x6e, 0x1d, 0x29, 0x94, 0xd3, 0xf4, 0x00, 0xf5, 0xdb, 0x54, 0x9e,
	0x30, 0x3c, 0xcd, 0x85, 0xc4, 0x18, 0x13, 0xad, 0xc8, 0xe7, 0x70, 0xe3, 0x20, 0x8f, 0x27, 0xc8,
	0xe3, 0x08, 0x95, 0x9a, 0x4a, 0x44, 0x35, 0x5c, 0x19, 0xad, 0xdc, 0xeb, 0x31, 0x92, 0xe4, 0x31,
	0x55, 0x0e, 0xa0, 0xda, 0x20, 0xe4, 0x13, 0x80, 0x97, 0xfc, 0xfc, 0x05, 0xd7, 0x98, 0x04, 0xef,
	0x86, 0x0d, 0xab, 0xd7, 0x8d, 0xf9, 0x39, 0x8d, 0x0a, 0x91, 0xff, 0x14, 0x36, 0xc7, 0x89, 0x46,
	0x39, 0xe3, 0x01, 0xee, 0xf1, 0x8c, 0xbf, 0x16, 0x91, 0xd0, 0x02, 0x15, 0xb9, 0x07, 0x1b, 0xaf,
	0x22, 0x9e, 0x4c, 0xf9, 0xb1, 0x15, 0x47, 0x68, 0xa3, 0x74, 0xd8, 0x8d, 0xb3, 0x88, 0x27, 0x54,
	0xf3, 0x63, 0x1a, 0x14, 0x72, 0xff, 0x5b, 0xe8, 0x4c, 0xb4, 0x44, 0x1e, 0x8f, 0xc3, 0x22, 0x5e,
	0xf0, 0x34, 0x0c, 0x25, 0xaa, 0x22, 0x2f, 0xcf, 0xc4, 0x0b, 0x28, 0x2f, 0x44, 0xe4, 0x43, 0xe8,
	0x1c, 0x25, 0xe2, 0x34, 0xc7, 0x71, 0x68, 0xd3, 0xf1, 0x98, 0x97, 0xdb, 0x33, 0x15, 0xa1, 0x7f,
	0x04, 0xdd, 0x2a, 0x99, 0xf7, 0x71, 0x76, 0x17, 0x7a, 0x95, 0xfe, 0x01, 0x8f, 0xd1, 0x79, 0xdc,
	0x10, 0xa5, 0x90, 0x26, 0x3c, 0x46, 0xff, 0x67, 0xf0, 0x2a, 0x35, 0xd2, 0x87, 0xb5, 0x71, 0x12,
	0xe2, 0xb9, 0xf5, 0xb7, 0xca, 0xd6, 0x84, 0x39, 0x90, 0x27, 0x0b, 0x91, 0xad, 0x9f, 0xee, 0x83,
	0xad, 0xed, 0x79, 0x53, 0xb6, 0x6b, 0x30, 0x5b, 0x9f, 0x07, 0x10, 0xa1, 0xff, 0x57, 0x03, 0x7a,
	0x2f, 0x84, 0xd2, 0x98, 0xa0, 0xfc, 0x46, 0xa6, 0x79, 0xb6, 0x18, 0xa3, 0x57, 0xc6, 0xd8, 0x86,
	0xb5, 0x89, 0x96, 0x95, 0xf7, 0x7e, 0xdd, 0x7b, 0x59, 0x40, 0xe6, 0x29, 0xfb, 0x8f, 0x8a, 0x90,
	0x7c, 0x07, 0xfd, 0x67, 0x49, 0x38, 0xd1, 0x96, 0x26, 0x55, 0x78, 0x35, 0x5c, 0x1d, 0xad, 0xde,
	0xeb, 0x3e, 0xd8, 0x5c, 0x9a, 0x1c, 0x1b, 0x60, 0x12, 0x52, 0x55, 0xd8, 0xd0, 0x2a, 0x4d, 0x45,
	0x7e, 0x80, 0xf5, 0x8a, 0x53, 0x0c, 0x4f, 0x87, 0x4d, 0x9b, 0xc3, 0xdd, 0xba, 0x93, 0x6b, 0x39,
	0xc7, 0xee, 0xe4, 0x0a, 0x25, 0xd5, 0x29, 0x4d, 0x0a, 0x90, 0xca, 0x3a, 0x23, 0x5f, 0x94, 0xe5,
	0xdd, 0xe3, 0xd9, 0x70, 0xcd, 0xfa, 0xfd, 0x74, 0x69, 0x72, 0x75, 0x7e, 0xb1, 0xc1, 0xbc, 0x86,
	0x41, 0x4d, 0xee, 0x8f, 0x00, 0x8a, 0x62, 0x30, 0x9e, 0x9c, 0x10, 0x02, 0x4d, 0xf3, 0xeb, 0x0a,
	0xd9, 0x94, 0x3c, 0x39, 0xf1, 0x7f, 0x81, 0x8d, 0x31, 0x22, 0xce, 0xa9, 0x41, 0x76, 0x60, 0x63,
	0x1f, 0x95, 0x16, 0x89, 0xbd, 0xf6, 0x4b, 0x1e, 0x38, 0xb2, 0x6c, 0x85, 0x73, 0x29, 0xad, 0x13,
	0xe7, 0x23, 0xf0, 0x26, 0x69, 0x2e, 0x03, 0xe3, 0xc4, 0x91, 0x06, 0x94, 0x15, 0x18, 0x35, 0xff,
	0x15, 0x74, 0x4d, 0x04, 0xc7, 0x7f, 0xb2, 0x0d, 0x1f, 0x1c, 0x4a, 0x91, 0x4a, 0xa1, 0xdf, 0xed,
	0xa5, 0x21, 0x1e, 0xa6, 0x22, 0xd1, 0x2e, 0xa3, 0x9b, 0x99, 0x03, 0x68, 0x90, 0x86, 0x48, 0x33,
	0x03, 0x91, 0x2d, 0x68, 0x19, 0x53, 0xd7, 0xe9, 0x1e, 0x6b, 0xdb, 0x91, 0x11, 0xa1, 0xff, 0xe7,
	0x0a, 0x78, 0xe3, 0xec, 0x6c, 0x77, 0x9a, 0x67, 0x11, 0x92, 0x8f, 0xc1, 0x9b, 0xc8, 0x60, 0x9c,
	0x99, 0x5b, 0x94, 0xec, 0x56, 0x32, 0xa0, 0x22, 0xb3, 0x79, 0x92, 0x11, 0x80, 0xb9, 0x95, 0x53,
	0x28, 0xb2, 0x5c, 0x37, 0x37, 0xaa, 0x34, 0x08, 0x34, 0xf7, 0x55, 0x90, 0x0d, 0x57, 0x8b, 0xea,
	0x84, 0x2a, 0xc8, 0xc8, 0x6d, 0xe8, 0x1c, 0x9a, 0x17, 0x25, 0x48, 0x23, 0xdb, 0xe4, 0x1e, 0xeb,
	0x64, 0xee, 0x4c, 0x6e, 0x41, 0x7b, 0x22, 0x83, 0xc3, 0x54, 0x6a, 0xdb, 0xa7, 0x1e, 0xeb, 0x98,
	0x78, 0x59, 0x2a, 0xb5, 0x99, 0x4b, 0x13, 0xcc, 0x62, 0x2d, 0x8b, 0x79, 0x36, 0x94, 0x01, 0xcb,
	0xbc, 0x1f, 0xfd, 0xdf, 0xf2, 0xfe, 0xb5, 0x01, 0x83, 0x7d, 0xae, 0xf9, 0xd7, 0x92, 0xc7, 0x38,
	0xc9, 0x30, 0x10, 0x33, 0x11, 0x58, 0x36, 0x5c, 0x33, 0xa2, 0x5f, 0x41, 0xdb, 0xd1, 0xca, 0x0d,
	0xe9, 0xed, 0x05, 0x22, 0x2f, 0xb0, 0x8e, 0x6d, 0x0a, 0x44, 0x7c, 0x7c, 0xff, 0x41, 0x9d, 0x59,
	0xa8, 0xc8, 0x13, 0x68, 0x3b, 0xe2, 0xd8, 0xfb, 0x5d, 0x7e, 0x46, 0xe6, 0xbc, 0x62, 0x37, 0x4a,
	0x07, 0xe5, 0x93, 0x4a, 0x76, 0xa0, 0xed, 0xf8, 0xe1, 0x06, 0x74, 0x71, 0xca, 0x4b, 0xea, 0xb0,
	0xb6, 0xc8, 0xce, 0x76, 0x75, 0x9e, 0x39, 0x03, 0xd3, 0x18, 0x37, 0x79, 0x97, 0x0d, 0x1e, 0xcd,
	0x0d, 0x1e, 0xe9, 0x3c, 0xf3, 0x9f, 0x43, 0xc7, 0xce, 0xe3, 0x19, 0x8f, 0xc8, 0x1d, 0xf0, 0x0e,
	0xf2, 0x18, 0x25, 0xd7, 0xa9, 0x74, 0x75, 0xf0, 0x92, 0x52, 0x40, 0x46, 0xd0, 0xdd, 0xc7, 0x24,
	0x8d, 0xcd, 0xfc, 0xa4, 0xb2, 0xdc, 0x1d, 0xe1, 0x5c, 0xe4, 0xff, 0xbe, 0x02, 0xde, 0x54, 0xc4,
	0xf8, 0xf4, 0x2d, 0x97, 0x48, 0x1e, 0xc3, 0xe0, 0x19, 0x97, 0x91, 0x40, 0xa5, 0xa7, 0x92, 0x27,
	0x2a, 0x16, 0xfa, 0xfb, 0xd9, 0x4c, 0x61, 0x39, 0x2a, 0x43, 0x74, 0x28, 0xd5, 0x0e, 0xa6, 0xa9,
	0xc5, 0xc9, 0x2e, 0xf4, 0xcd, 0x86, 0xba, 0x62, 0x57, 0x84, 0x1c, 0x44, 0x16, 0xbb, 0x62, 0x35,
	0x80, 0xd6, 0x73, 0xa1, 0x35, 0x4a, 0x47, 0xa3, 0xd6, 0x1b, 0x7b, 0xf2, 0x7f, 0x6b, 0x40, 0x7f,
	0x2a, 0xf9, 0x6c, 0x26, 0x82, 0xc5, 0x96, 0xdf, 0x9f, 0x5f, 0xdd, 0xa6, 0x74, 0xe9, 0x09, 0x2e,
	0x31, 0xd6, 0x11, 0x65, 0x81, 0x1e, 0x42, 0xff, 0x25, 0x3f, 0xb7, 0xec, 0x51, 0x87, 0x28, 0x2b,
	0xeb, 0x22, 0xb1, 0x2d, 0xb3, 0x47, 0x67, 0x16, 0xa4, 0x19, 0x4a, 0x5a, 0x99, 0x7d, 0x06, 0xeb,
	0xa5, 0xd9, 0x44, 0x5c, 0xa0, 0xcb, 0x6f, 0xa3, 0x52, 0xa7, 0x4a, 0x5c, 0x20, 0x79, 0x08, 0x9b,
	0xee, 0xbe, 0x4a, 0x89, 0x34, 0x99, 0x60, 0x84, 0x81, 0xc9, 0xd3, 0xb1, 0x7f, 0xa0, 0x6b, 0x20,
	0x55, 0x25, 0x4a, 0x76, 0x6b, 0x35, 0x5f, 0xd6, 0xf3, 0x0a, 0x64, 0xa0, 0x45, 0x8c, 0x94, 0x9b,
	0xff, 0xfe, 0x1f, 0x4d, 0xe8, 0x4e, 0x79, 0x74, 0x52, 0x6e, 0xa8, 0x6a, 0x17, 0xad, 0xbc, 0xdf,
	0x2e, 0xda, 0x85, 0xf6, 0x44, 0x4b, 0xfb, 0x14, 0x17, 0x83, 0x31, 0xb8, 0x6a, 0x61, 0x50, 0xd6,
	0x75, 0x36, 0xe6, 0xa5, 0xfe, 0x77, 0x37, 0xd8, 0x4f, 0xd7, 0xcd, 0xf2, 0xb0, 0x69, 0xdd, 0xf9,
	0x75, 0x77, 0xcb, 0x35, 0xd9, 0x30, 0xe4, 0x9a, 0x97, 0x4d, 0x58, 0x20, 0xc7, 0xd1, 0x72, 0xd2,
	0xb8, 0x0a, 0x8f, 0x16, 0x2a, 0xbc, 0x44, 0x8f, 0x6d, 0xea, 0x42, 0x7a, 0xc9, 0xed, 0xe5, 0xb5,
	0xdb, 0xfa, 0x8f, 0xd6, 0x6e, 0xfb, 0x9f, 0xae, 0xdd, 0x0b, 0x68, 0x9b, 0xd8, 0xa8, 0x34, 0xd9,
	0x81, 0x56, 0x41, 0x15, 0x47, 0x8e, 0x85, 0xf7, 0xab, 0x46, 0x22, 0xd6, 0xd2, 0xf6, 0x40, 0xbe,
	0x84, 0xf5, 0xf2, 0xfb, 0xc7, 0xfc, 0x0e, 0x1b, 0xb6, 0x1f, 0xb7, 0xea, 0x66, 0x0b, 0xdf, 0x47,
	0xac, 0x17, 0xb9, 0x23, 0x35, 0x7f, 0xfc, 0x1f, 0xa1, 0xb7, 0x67, 0x3f, 0x89, 0xcb, 0x0c, 0x86,
	0xd0, 0x7e, 0x85, 0xd2, 0x10, 0xdf, 0xa6, 0xd0, 0x60, 0xed, 0xb3, 0xe2, 0x48, 0x76, 0xa0, 0xe3,
	0x94, 0x94, 0x0b, 0x73, 0xb3, 0x1e, 0xc6, 0x61, 0xac, 0x23, 0x9d, 0xd2, 0xeb, 0x96, 0x5d, 0x22,
	0x5f, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xbb, 0xb3, 0x57, 0x75, 0x0b, 0x00, 0x00,
}
