// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package structures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_ADD_STREAM    EventType = 0
	EventType_REMOVE_STREAM EventType = 1
)

var EventType_name = map[int32]string{
	0: "ADD_STREAM",
	1: "REMOVE_STREAM",
}

var EventType_value = map[string]int32{
	"ADD_STREAM":    0,
	"REMOVE_STREAM": 1,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type EventStatus int32

const (
	EventStatus_PLANNED EventStatus = 0
	EventStatus_PASSED  EventStatus = 1
)

var EventStatus_name = map[int32]string{
	0: "PLANNED",
	1: "PASSED",
}

var EventStatus_value = map[string]int32{
	"PLANNED": 0,
	"PASSED":  1,
}

func (x EventStatus) String() string {
	return proto.EnumName(EventStatus_name, int32(x))
}

func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

type EventHandler struct {
	Handler              string   `protobuf:"bytes,1,opt,name=Handler,proto3" json:"Handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventHandler) Reset()         { *m = EventHandler{} }
func (m *EventHandler) String() string { return proto.CompactTextString(m) }
func (*EventHandler) ProtoMessage()    {}
func (*EventHandler) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *EventHandler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventHandler.Unmarshal(m, b)
}
func (m *EventHandler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventHandler.Marshal(b, m, deterministic)
}
func (m *EventHandler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventHandler.Merge(m, src)
}
func (m *EventHandler) XXX_Size() int {
	return xxx_messageInfo_EventHandler.Size(m)
}
func (m *EventHandler) XXX_DiscardUnknown() {
	xxx_messageInfo_EventHandler.DiscardUnknown(m)
}

var xxx_messageInfo_EventHandler proto.InternalMessageInfo

func (m *EventHandler) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

type LogInfo struct {
	Info                 string   `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfo.Unmarshal(m, b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return xxx_messageInfo_LogInfo.Size(m)
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type Event struct {
	EventId              string          `protobuf:"bytes,1,opt,name=EventId,proto3" json:"EventId,omitempty"`
	EventType            EventType       `protobuf:"varint,2,opt,name=EventType,proto3,enum=structures.EventType" json:"EventType,omitempty"`
	Status               EventStatus     `protobuf:"varint,3,opt,name=Status,proto3,enum=structures.EventStatus" json:"Status,omitempty"`
	Handlers             []*EventHandler `protobuf:"bytes,4,rep,name=Handlers,proto3" json:"Handlers,omitempty"`
	EventGroupId         string          `protobuf:"bytes,5,opt,name=EventGroupId,proto3" json:"EventGroupId,omitempty"`
	ExecutionTime        uint32          `protobuf:"varint,6,opt,name=ExecutionTime,proto3" json:"ExecutionTime,omitempty"`
	OccuranceTime        uint32          `protobuf:"varint,7,opt,name=OccuranceTime,proto3" json:"OccuranceTime,omitempty"`
	Duration             uint32          `protobuf:"varint,8,opt,name=Duration,proto3" json:"Duration,omitempty"`
	LogInfo              *LogInfo        `protobuf:"bytes,9,opt,name=LogInfo,proto3" json:"LogInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_ADD_STREAM
}

func (m *Event) GetStatus() EventStatus {
	if m != nil {
		return m.Status
	}
	return EventStatus_PLANNED
}

func (m *Event) GetHandlers() []*EventHandler {
	if m != nil {
		return m.Handlers
	}
	return nil
}

func (m *Event) GetEventGroupId() string {
	if m != nil {
		return m.EventGroupId
	}
	return ""
}

func (m *Event) GetExecutionTime() uint32 {
	if m != nil {
		return m.ExecutionTime
	}
	return 0
}

func (m *Event) GetOccuranceTime() uint32 {
	if m != nil {
		return m.OccuranceTime
	}
	return 0
}

func (m *Event) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetLogInfo() *LogInfo {
	if m != nil {
		return m.LogInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("structures.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("structures.EventStatus", EventStatus_name, EventStatus_value)
	proto.RegisterType((*EventHandler)(nil), "structures.EventHandler")
	proto.RegisterType((*LogInfo)(nil), "structures.LogInfo")
	proto.RegisterType((*Event)(nil), "structures.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x5f, 0x4b, 0xeb, 0x40,
	0x10, 0xc5, 0x9b, 0xfe, 0x49, 0xda, 0xc9, 0x6d, 0xe9, 0x9d, 0xcb, 0xc5, 0x45, 0x10, 0x42, 0x10,
	0x09, 0x05, 0x23, 0xb4, 0x7e, 0x81, 0x40, 0x82, 0x16, 0xfa, 0x8f, 0x4d, 0xf1, 0x55, 0x62, 0xba,
	0x4a, 0x41, 0x93, 0xb2, 0xd9, 0x15, 0xfd, 0xe6, 0x3e, 0x4a, 0xb6, 0x9b, 0xb4, 0xa5, 0x4f, 0x99,
	0x99, 0xf3, 0x3b, 0xc3, 0xe4, 0xb0, 0x60, 0xb3, 0x4f, 0x96, 0x09, 0x7f, 0xc7, 0x73, 0x91, 0x23,
	0x14, 0x82, 0xcb, 0x54, 0x48, 0xce, 0x0a, 0xd7, 0x83, 0x3f, 0x51, 0x29, 0x3d, 0x26, 0xd9, 0xe6,
	0x9d, 0x71, 0x24, 0x60, 0xe9, 0x92, 0x18, 0x8e, 0xe1, 0xf5, 0x68, 0xd5, 0xba, 0x57, 0x60, 0xcd,
	0xf2, 0xb7, 0x69, 0xf6, 0x9a, 0x23, 0x42, 0xbb, 0xfc, 0x6a, 0x42, 0xd5, 0xee, 0x4f, 0x13, 0x3a,
	0x6a, 0x53, 0xb9, 0x42, 0x15, 0xd3, 0x4d, 0xb5, 0x42, 0xb7, 0x38, 0x81, 0x9e, 0x2a, 0xd7, 0xdf,
	0x3b, 0x46, 0x9a, 0x8e, 0xe1, 0x0d, 0xc6, 0xff, 0xfd, 0xc3, 0x31, 0x7e, 0x2d, 0xd2, 0x03, 0x87,
	0x77, 0x60, 0xc6, 0x22, 0x11, 0xb2, 0x20, 0x2d, 0xe5, 0xb8, 0x38, 0x73, 0xec, 0x65, 0xaa, 0x31,
	0xbc, 0x87, 0xae, 0xbe, 0xb9, 0x20, 0x6d, 0xa7, 0xe5, 0xd9, 0x63, 0x72, 0x66, 0xd1, 0x00, 0xad,
	0x49, 0x74, 0x75, 0x10, 0x0f, 0x3c, 0x97, 0xbb, 0xe9, 0x86, 0x74, 0xd4, 0xe9, 0x27, 0x33, 0xbc,
	0x86, 0x7e, 0xf4, 0xc5, 0x52, 0x29, 0xb6, 0x79, 0xb6, 0xde, 0x7e, 0x30, 0x62, 0x3a, 0x86, 0xd7,
	0xa7, 0xa7, 0xc3, 0x92, 0x5a, 0xa6, 0xa9, 0xe4, 0x49, 0x96, 0x32, 0x45, 0x59, 0x7b, 0xea, 0x64,
	0x88, 0x97, 0xd0, 0x0d, 0x25, 0x4f, 0x4a, 0x17, 0xe9, 0x2a, 0xa0, 0xee, 0xf1, 0xb6, 0x8e, 0x9a,
	0xf4, 0x1c, 0xc3, 0xb3, 0xc7, 0xff, 0x8e, 0x7f, 0x40, 0x4b, 0xb4, 0x62, 0x46, 0xfe, 0x51, 0xac,
	0x38, 0x00, 0x08, 0xc2, 0xf0, 0x39, 0x5e, 0xd3, 0x28, 0x98, 0x0f, 0x1b, 0xf8, 0x17, 0xfa, 0x34,
	0x9a, 0x2f, 0x9f, 0xa2, 0x6a, 0x64, 0x8c, 0x6e, 0xc0, 0x3e, 0xca, 0x0d, 0x6d, 0xb0, 0x56, 0xb3,
	0x60, 0xb1, 0x88, 0xc2, 0x61, 0x03, 0x01, 0xcc, 0x55, 0x10, 0xc7, 0x51, 0x38, 0x34, 0x5e, 0x4c,
	0xf5, 0x5c, 0x26, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xae, 0x4a, 0x43, 0x3d, 0x02, 0x00,
	0x00,
}
